name: SkyWarsMR
author: Mike Rangel
main: MikeRangel\SkyWars\SkyWars
version: 1.0.0
api: [1.0.0, 2.0.0, 3.0.0, 4.0.0, 5.0.0]
website: ''
permissions:
  skywars.command:
    description: "Allows use of SkyWars commands"
    default: true